package com.anthropic.claude.tool.custom

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * Sealed interface for events emitted by the Phone Call Monitor tool.
 * Used for real-time streaming of phone call transcription and agent responses.
 */
@Serializable
sealed interface PhoneCallMonitorEvent {

    /** A transcript segment spoken by the user (caller). */
    @Serializable
    @SerialName("user_transcript")
    data class UserTranscript(val payload: Payload? = null) : PhoneCallMonitorEvent {
        @Serializable
        data class Payload(
            val transcript: String? = null,
            @SerialName("is_final") val isFinal: Boolean = false,
        )
    }

    /** A response generated by the agent during the call. */
    @Serializable
    @SerialName("agent_response")
    data class AgentResponse(val payload: Payload? = null) : PhoneCallMonitorEvent {
        @Serializable
        data class Payload(
            val text: String? = null,
            @SerialName("is_final") val isFinal: Boolean = false,
        )
    }

    /** A corrected version of a previous agent response. */
    @Serializable
    @SerialName("agent_response_correction")
    data class AgentResponseCorrection(val payload: Payload? = null) : PhoneCallMonitorEvent {
        @Serializable
        data class Payload(
            @SerialName("corrected_text") val correctedText: String? = null,
            @SerialName("original_text") val originalText: String? = null,
        )
    }

    /** Metadata event (e.g. call ID, participant info). */
    @Serializable
    @SerialName("meta")
    data class Meta(val data: JsonElement? = null) : PhoneCallMonitorEvent

    /** Signals that the call has ended and post-processing is underway. */
    @Serializable
    @SerialName("call_ended_processing")
    data object CallEndedProcessing : PhoneCallMonitorEvent

    /** Catch-all for unknown/future event types. */
    @Serializable
    @SerialName("unknown")
    data class Unknown(val raw: JsonElement? = null) : PhoneCallMonitorEvent
}
