package com.anthropic.claude.sessions.types

import com.anthropic.claude.types.strings.SessionId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

// ─── Enums ───────────────────────────────────────────────────────────────────

/**
 * Lifecycle status of a Claude session.
 * Exact server values extracted from Smali bytecode.
 */
@Serializable
enum class SessionStatus {
    @SerialName("unknown") UNKNOWN,
    @SerialName("pending") PENDING,
    @SerialName("requires_action") REQUIRES_ACTION,
    @SerialName("running") RUNNING,
    @SerialName("idle") IDLE,
    @SerialName("archived") ARCHIVED,
}

/**
 * WebSocket / transport connection status of a session.
 */
@Serializable
enum class ConnectionStatus {
    @SerialName("unknown") UNKNOWN,
    @SerialName("connected") CONNECTED,
    @SerialName("disconnected") DISCONNECTED,
}

/**
 * Status of the backend worker processing the session.
 */
@Serializable
enum class WorkerStatus {
    @SerialName("unknown") UNKNOWN,
    @SerialName("processing") PROCESSING,
    @SerialName("idle") IDLE,
}

// ─── Supporting models ────────────────────────────────────────────────────────

/**
 * Information about a connected client (platform + heartbeat).
 */
@Serializable
data class ClientPresenceInfo(
    val platform: String? = null,
    @SerialName("client_id") val clientId: String? = null,
    @SerialName("last_pulse_at") val lastPulseAt: String? = null,
)

/**
 * External metadata attached to a session (e.g. pending action from external system).
 */
@Serializable
data class SessionExternalMetadata(
    @SerialName("pending_action") val pendingAction: String? = null,
)

/**
 * Post-turn summary generated by the model at the end of each turn.
 * Used in Tasks / agentic workflows to surface status and next steps.
 */
@Serializable
data class PostTurnSummary(
    @SerialName("status_category") val statusCategory: String? = null,
    @SerialName("status_detail") val statusDetail: String? = null,
    @SerialName("is_noteworthy") val isNoteworthy: Boolean = false,
    val title: String? = null,
    @SerialName("recent_action") val recentAction: String? = null,
    @SerialName("needs_action") val needsAction: String? = null,
    val description: String? = null,
    @SerialName("artifact_urls") val artifactUrls: List<String>? = null,
)

/**
 * A source document/file available within the session's context.
 */
@Serializable
data class SessionContextSource(
    val type: String? = null,
    val id: String? = null,
    val name: String? = null,
)

/**
 * A desired outcome configured for the session.
 */
@Serializable
data class Outcome(
    val type: String? = null,
    val description: String? = null,
)

/**
 * The execution context of a session — working directory, sources, model, and prompts.
 */
@Serializable
data class SessionContext(
    val sources: List<SessionContextSource>? = null,
    val cwd: String? = null,
    val outcomes: List<Outcome>? = null,
    @SerialName("custom_system_prompt") val customSystemPrompt: String? = null,
    @SerialName("append_system_prompt") val appendSystemPrompt: String? = null,
    val model: String? = null,
)

// ─── Session Resource ─────────────────────────────────────────────────────────

/**
 * Full server-side representation of a Claude Session (agentic / SDK sessions).
 * 17 fields from the 83 KB SessionResource.smali.
 */
@Serializable
data class SessionResource(
    val type: String? = null,
    val id: SessionId? = null,
    val title: String? = null,
    @SerialName("session_status") val sessionStatus: SessionStatus? = null,
    @SerialName("environment_id") val environmentId: String? = null,
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null,
    @SerialName("session_context") val sessionContext: SessionContext? = null,
    @SerialName("bridge_spawn_path") val bridgeSpawnPath: String? = null,
    @SerialName("connection_status") val connectionStatus: ConnectionStatus? = null,
    @SerialName("worker_status") val workerStatus: WorkerStatus? = null,
    @SerialName("client_presence") val clientPresence: List<ClientPresenceInfo>? = null,
    @SerialName("trigger_id") val triggerId: String? = null,
    val origin: String? = null,
    @SerialName("post_turn_summary") val postTurnSummary: PostTurnSummary? = null,
    @SerialName("task_summary") val taskSummary: String? = null,
    @SerialName("external_metadata") val externalMetadata: SessionExternalMetadata? = null,
)

// ─── SDK Message Event ────────────────────────────────────────────────────────

/**
 * Stub for SDK messages — full model defined in SdkMessage.kt.
 */
@Serializable
data class SdkMessage(
    val role: String? = null,
    val content: JsonElement? = null,
)

/**
 * An event carrying an SDK message within a session.
 * Streamed via the Conway WebSocket connection.
 */
@Serializable
data class SdkMessageEvent(
    val type: String? = null,
    val uuid: String? = null,
    @SerialName("session_id") val sessionId: String? = null,
    @SerialName("parent_tool_use_id") val parentToolUseId: String? = null,
    val message: SdkMessage? = null,
    @SerialName("tool_use_result") val toolUseResult: JsonElement? = null,
    val error: Boolean? = null,
    @SerialName("file_attachments") val fileAttachments: List<JsonElement>? = null,
    @SerialName("created_at") val createdAt: String? = null,
)

// ─── Shared Session ───────────────────────────────────────────────────────────

/**
 * Paginated payload returned when fetching a shared session's event history.
 */
@Serializable
data class SharedSessionData(
    val data: List<JsonElement>? = null,
    val session: SessionResource? = null,
    @SerialName("sharer_display_name") val sharerDisplayName: String? = null,
    val type: String? = null,
    @SerialName("has_more") val hasMore: Boolean = false,
    @SerialName("first_id") val firstId: String? = null,
    @SerialName("last_id") val lastId: String? = null,
)
